BEGIN;

CREATE TABLE payment_transaction (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT NOT NULL,
    transaction_id VARCHAR(255) NOT NULL,
    payment_method payment_mode_enum NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_transaction_booking FOREIGN KEY (booking_id) REFERENCES booking(id) ON DELETE CASCADE
);

CREATE INDEX idx_payment_transaction_booking_id ON payment_transaction(booking_id);

COMMIT;
