BEGIN;

CREATE TABLE customer_wallet (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(30) UNIQUE NOT NULL,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_wallet_username FOREIGN KEY (username) REFERENCES customertable(username) ON DELETE CASCADE,
    CONSTRAINT check_balance CHECK (balance >= 0)
);

CREATE INDEX idx_wallet_username ON customer_wallet(username);

COMMIT;
